# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: azimuth_joint
  pid: {p: 200.0, i: 10, d: 50.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: elevation_joint
  pid: {p: 5000.0, i: 10, d: 200.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_02__link_03_joint
  pid: {p: 2000.0, i: 5, d: 100.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_03__link_04_joint
  pid: {p: 200.0, i: 5, d: 20.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_04__link_05_joint
  pid: {p: 70.0, i: 5, d: 7.0}
