# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
shoulder_azimuth_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_azimuth_joint
  pid: {p: 200.0, i: 10, d: 50.0}
shoulder_elevation_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_elevation_joint
  pid: {p: 5000.0, i: 10, d: 200.0}
elbow_pivot_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: elbow_pivot_joint
  pid: {p: 2000.0, i: 5, d: 100.0}
wrist_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_pitch_joint
  pid: {p: 200.0, i: 5, d: 20.0}
wrist_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_yaw_joint
  pid: {p: 70.0, i: 5, d: 7.0}
