<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Import arm parameters -->
    <xacro:include filename="$(find oberon7_description)/urdf/parameters/serial_arm.xacro" />

    <!-- Transmission Macro -->
    <!-- <xacro:macro name="simple_transmission" params="joint">
        <transmission name="${joint}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint}_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro> -->


    <!-- Transmission Macro -->
    <xacro:macro name="simple_transmission" params="joint">
      <transmission name="${joint}_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${joint}">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${joint}_motor">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:macro>



    <xacro:macro name="oberon7_serial_arm" params="namespace">

        <!-- Ground base -->

        <link name="${namespace}/base">
            <xacro:link_box_inertial mass="${total_mass * base_volume / total_volume_bbox}"
                        width="${base_width}"
                        length="${base_length}"
                        height="${base_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:link_box_inertial>

            <!-- <visual>
                <origin xyz="0 0 ${-0.15776/2+0.015776/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="0.197 0.197 0.015776"/>
                </geometry>
            </visual> -->

        </link>

        <!-- Shoulder link -->
        <xacro:property name="base_height" value="0.203"/>

        <link name="${namespace}/shoulder_link">
            <xacro:link_box_inertial mass="${total_mass * shoulder_link_volume / total_volume_bbox}"
                        width="${shoulder_link_width}"
                        length="${shoulder_link_length}"
                        height="${shoulder_link_height}">
                <origin xyz="${shoulder_link_com}" rpy="0 0 0"/>
            </xacro:link_box_inertial>

            <visual>
                <origin xyz="0 0 ${-base_height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${0.0985}" length="${base_height}" />
                </geometry>
            </visual>
        </link>

        <joint name="${namespace}/azimuth" type="revolute">
            <origin xyz="0 0 ${0.203/2}" rpy="0 0 0"/>
            <parent link="${namespace}/base"/>
            <child link="${namespace}/shoulder_link"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="50" friction="200"/> -->
            <dynamics damping="100" friction="150"/>
            <limit lower="${-60 * d2r}" upper="${60 * d2r}" velocity="0.17" effort="200"/>
            <!-- <limit lower="${-60 * d2r}" upper="${60 * d2r}" velocity="0.17" effort="1000"/> -->
        </joint>

        <xacro:simple_transmission joint="${namespace}/azimuth" />

        <!-- UPPER ARM -->
        <xacro:property name="upper_arm_l" value="${0.939}"/>

        <link name="${namespace}/upper_arm">
            <xacro:link_box_inertial mass="${total_mass * upper_arm_volume / total_volume_bbox}"
                        width="${upper_arm_width}"
                        length="${upper_arm_length}"
                        height="${upper_arm_height}">
                <origin xyz="${upper_arm_com}" rpy="0 0 0"/>
            </xacro:link_box_inertial>

            <visual>
                <origin xyz="${upper_arm_l/2} 0 0" rpy="0 ${0.5*pi} 0"/>
                <geometry>
                    <cylinder radius="${0.5 * upper_arm_width}" length="${upper_arm_l}"/>
                </geometry>
            </visual>

            <!-- <collision>
                <origin xyz="0.312501 0 0" rpy="0 ${0.5*pi} 0"/>
                <geometry>
                    <cylinder radius="${0.5 * upper_arm_width}" length="${upper_arm_length+.34712}"/>
                </geometry>
            </collision> -->
        </link>

        <joint name="${namespace}/shoulder" type="revolute">
            <parent link="${namespace}/shoulder_link"/>
            <child link="${namespace}/upper_arm"/>
            <origin xyz="0.1 0 0" rpy="${0.5*pi} 0 0"/>
            <!-- <origin xyz="0 0 0.1" rpy="${0.5*pi} 0 0"/> -->
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="50" friction="200"/> -->
            <dynamics damping="50" friction="150"/>
            <limit lower="${-90 * d2r}" upper="${90 * d2r}" velocity=".17" effort="5000"/>
            <!-- <limit lower="${-90 * d2r}" upper="${90 * d2r}" velocity=".17" effort="1000"/> -->
        </joint>

        <xacro:simple_transmission joint="${namespace}/shoulder" />

        <!-- ELBOW LINK -->

        <link name="${namespace}/elbow_link">
            <xacro:link_box_inertial mass="${total_mass * elbow_link_volume / total_volume_bbox}"
                        width="${elbow_link_width}"
                        length="${elbow_link_length}"
                        height="${elbow_link_height}">
                <origin xyz="${elbow_link_com}" rpy="0 0 0"/>
            </xacro:link_box_inertial>

            <visual>
                <origin xyz="0.125269 ${-elbow_link_length/2-forearm_height/2} 0.0" rpy="0 ${0.5*pi} ${0.5*pi}"/>
                <!-- <origin xyz="0.125269 ${-forearm_height/2} 0.0" rpy="0 ${0.5*pi} ${0.5*pi}"/> -->
                <geometry>
                    <cylinder radius="${0.5 * elbow_link_height}" length="${elbow_link_length+forearm_height}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.125269 ${-elbow_link_length/2-forearm_height/2} 0.0" rpy="0 ${0.5*pi} ${0.5*pi}"/>
                <geometry>
                    <cylinder radius="${0.5 * elbow_link_height}" length="${elbow_link_length/3+forearm_height/3}"/>
                </geometry>
            </collision>
        </link>

        <joint name="${namespace}/elbow" type="revolute">
            <parent link="${namespace}/upper_arm"/>
            <child link="${namespace}/elbow_link"/>
            <origin xyz="${upper_arm_l-0.064} 0 0" rpy="0 0 0"/>
            <!-- <dynamics damping="50" friction="200"/> -->
            <dynamics damping="50" friction="150"/>
            <axis xyz="0 0 1"/>
            <limit lower="${-90 * d2r}" upper="${60 * d2r}" velocity=".15" effort="300"/>
            <!-- <limit lower="${-90 * d2r}" upper="${60 * d2r}" velocity=".13" effort="1000"/> -->
        </joint>

        <xacro:simple_transmission joint="${namespace}/elbow" />

        <!-- WRIST 1  -->

        <link name="${namespace}/wrist_link">
            <xacro:link_box_inertial mass="${total_mass * wrist_volume / total_volume_bbox}"
                        width="${wrist_width}"
                        length="${wrist_length}"
                        height="${wrist_height}">
                <origin xyz="${wrist_com}" rpy="0 0 0"/>
            </xacro:link_box_inertial>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="file://$(find oberon7_description)/meshes/serial_arm/visual/Wrist.dae"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="${wrist_com}" rpy="0 ${0.5*pi} 0"/>
                <geometry>
                    <cylinder radius="${0.5 * wrist_height}" length="${wrist_length}"/>
                </geometry>
            </collision>
        </link>

        <joint name="${namespace}/pitch" type="revolute">
            <parent link="${namespace}/elbow_link"/>
            <child link="${namespace}/wrist_link"/>
            <!-- <origin xyz="${0.210} ${-0.525} 0" rpy="0 0 ${-0.5*PI}"/> -->
            <!-- <origin xyz="${0.1349014} ${-0.1936267/3-0.31595760629823427/3} 0" rpy="${-0*PI} ${-0*PI} ${-0.5*PI}"/> -->
            <origin xyz="${0.1349014} ${-0.1936267/3-0.31595760629823427/3} 0" rpy="${-0*PI} ${-0*PI} ${-0.5*PI}"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="50" friction="200"/> -->
            <dynamics damping="10" friction="10"/>
            <!-- <limit lower="${-90 * d2r}" upper="${90 * d2r}" velocity=".26" effort="200"/> -->
            <limit lower="${-90 * d2r}" upper="${90 * d2r}" velocity=".3" effort="50"/>
        </joint>

        <xacro:simple_transmission joint="${namespace}/pitch" />

        <!-- Adding parallel gripper  -->
        <xacro:include filename="$(find oberon7_description)/urdf/parallel_gripper.xacro" />
        
        <xacro:oberon7_gazebo_macro namespace="${namespace}"/>
    </xacro:macro>
</robot>
